version: 1.3.1
slug: ha_container_registry
name: Home Assistant Container Registry
description: A local container registry hosted by home assistant.
url: https://github.com/cjersey/home-assistant-custom-components/tree/main/add-ons/container-registry
arch:
  - amd64
startup: application
boot: auto
host_network: true
ingress: true
ingress_port: 0
ports:
  5000/tcp: null
ports_description:
  5000/tcp: Container Registry port
options:
stdin: true
image: registry:2.8.3