version: 2.8.3
slug: container_registry
name: Home Assistant Container Registry
description: A local container registry hosted by home assistant.
url: https://github.com/cjersey/home-assistant-custom-components/tree/main/add-ons/container-registry
arch:
  - amd64
  - i386
startup: application
boot: auto
host_network: true
# ingress: true
# ingress_port: 0
ports:
  5000/tcp: null
ports_description:
  5000/tcp: Container Registry port
image: registry:2.8.3